# PROJECT-3 :

# Social Media Sentiments Analysis

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
data = pd.read_csv(r'C:\Users\Talar\OneDrive\Desktop\python\python\sentimentdataset.csv')

 What is the overall distribution of sentiments (positive, negative, neutral) across the posts?2) Which platform generates the most engagement in terms of likes and retweets?3) Which users have the highest average engagement (likes and retweets per post)?

In [4]:
data.head(10)

,Unnamed: 0.1,Unnamed: 0,Text,Sentiment,Timestamp,User,Platform,Hashtags,Retweets,Likes,Country,Year,Month,Day,Hour
0,0,0,Enjoying a beautiful day at the park! ...,Positive,2023-01-15 12:30:00,User123,Twitter,#Nature #Park,15.0,30.0,USA,2023,1,15,12
1,1,1,Traffic was terrible this morning. ...,Negative,2023-01-15 08:45:00,CommuterX,Twitter,#Traffic #Morning,5.0,10.0,Canada,2023,1,15,8
2,2,2,Just finished an amazing workout! 💪 ...,Positive,2023-01-15 15:45:00,FitnessFan,Instagram,#Fitness #Workout,20.0,40.0,USA,2023,1,15,15
3,3,3,Excited about the upcoming weekend getaway! ...,Positive,2023-01-15 18:20:00,AdventureX,Facebook,#Travel #Adventure,8.0,15.0,UK,2023,1,15,18
4,4,4,Trying out a new recipe for dinner tonight. ...,Neutral,2023-01-15 19:55:00,ChefCook,Instagram,#Cooking #Food,12.0,25.0,Australia,2023,1,15,19
5,5,5,Feeling grateful for the little things in lif...,Positive,2023-01-16 09:10:00,GratitudeNow,Twitter,#Gratitude #PositiveVibes,25.0,50.0,India,2023,1,16,9
6,6,6,Rainy days call for cozy blankets and hot coc...,Positive,2023-01-16 14:45:00,RainyDays,Facebook,#RainyDays #Cozy,10.0,20.0,Canada,2023,1,16,14
7,7,7,The new movie release is a must-watch! ...,Positive,2023-01-16 19:30:00,MovieBuff,Instagram,#MovieNight #MustWatch,15.0,30.0,USA,2023,1,16,19
8,8,8,Political discussions heating up on the timel...,Negative,2023-01-17 08:00:00,DebateTalk,Twitter,#Politics #Debate,30.0,60.0,USA,2023,1,17,8
9,9,9,Missing summer vibes and beach days. ...,Neutral,2023-01-17 12:20:00,BeachLover,Facebook,#Summer #BeachDays,18.0,35.0,Australia,2023,1,17,12

In [5]:
data.tail(10)

,Unnamed: 0.1,Unnamed: 0,Text,Sentiment,Timestamp,User,Platform,Hashtags,Retweets,Likes,Country,Year,Month,Day,Hour
722,723,727,Winning a friendly sports competition against ...,Happy,2023-10-20 14:15:00,SportsVictoryHighSchool,Twitter,#SportsTriumph #HighSchoolAthletics,26.0,50.0,USA,2023,10,20,14
723,724,728,Receiving a heartfelt letter from a pen pal in...,Happy,2023-10-21 17:30:00,PenPalConnectionHighSchool,Facebook,#GlobalFriendship #HighSchoolCorrespondence,23.0,45.0,Canada,2023,10,21,17
724,725,729,Creating a beautiful mural with fellow art ent...,Happy,2023-10-22 20:45:00,MuralCreationHighSchool,Instagram,#ArtCollaboration #HighSchoolCreativity,22.0,43.0,UK,2023,10,22,20
725,726,730,Participating in a school-wide art exhibition....,Happy,2015-11-10 16:45:00,ArtExhibitionJoyHighSchool,Instagram,#ArtisticExpression #HighSchoolCreativity,23.0,44.0,USA,2015,11,10,16
726,727,731,Achieving a personal best in a track and field...,Happy,2016-09-14 12:30:00,TrackFieldSuccessHighSchool,Twitter,#AthleticAchievement #HighSchoolSports,26.0,51.0,Canada,2016,9,14,12
727,728,732,Collaborating on a science project that receiv...,Happy,2017-08-18 18:20:00,ScienceProjectSuccessHighSchool,Facebook,#ScienceFairWinner #HighSchoolScience,20.0,39.0,UK,2017,8,18,18
728,729,733,Attending a surprise birthday party organized ...,Happy,2018-06-22 14:15:00,BirthdayPartyJoyHighSchool,Instagram,#SurpriseCelebration #HighSchoolFriendship,25.0,48.0,USA,2018,6,22,14
729,730,734,Successfully fundraising for a school charity ...,Happy,2019-04-05 17:30:00,CharityFundraisingTriumphHighSchool,Twitter,#CommunityGiving #HighSchoolPhilanthropy,22.0,42.0,Canada,2019,4,5,17
730,731,735,"Participating in a multicultural festival, cel...",Happy,2020-02-29 20:45:00,MulticulturalFestivalJoyHighSchool,Facebook,#CulturalCelebration #HighSchoolUnity,21.0,43.0,UK,2020,2,29,20
731,732,736,Organizing a virtual talent show during challe...,Happy,2020-11-15 15:15:00,VirtualTalentShowSuccessHighSchool,Instagram,#VirtualEntertainment #HighSchoolPositivity,24.0,47.0,USA,2020,11,15,15

In [6]:
data.shape

(732, 15)

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 732 entries, 0 to 731
Data columns (total 15 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Unnamed: 0.1  732 non-null    int64
 1   Unnamed: 0    732 non-null    int64
 2   Text          732 non-null    object
 3   Sentiment     732 non-null    object
 4   Timestamp     732 non-null    object
 5   User          732 non-null    object
 6   Platform      732 non-null    object
 7   Hashtags      732 non-null    object
 8   Retweets      732 non-null    float64
 9   Likes         732 non-null    float64
 10  Country       732 non-null    object
 11  Year          732 non-null    int64
 12  Month         732 non-null    int64
 13  Day           732 non-null    int64
 14  Hour          732 non-null    int64
dtypes: float64(2), int64(6), object(7)
memory usage: 85.9+ KB

In [8]:
data.describe()

,Unnamed: 0.1,Unnamed: 0,Retweets,Likes,Year,Month,Day,Hour
count,732.000000,732.000000,732.000000,732.000000,732.000000,732.000000,732.000000,732.000000
mean,366.464481,369.740437,21.508197,42.901639,2020.471311,6.122951,15.497268,15.521858
std,211.513936,212.428936,7.061286,14.089848,2.802285,3.411763,8.474553,4.113414
min,0.000000,0.000000,5.000000,10.000000,2010.000000,1.000000,1.000000,0.000000
25%,183.750000,185.750000,17.750000,34.750000,2019.000000,3.000000,9.000000,13.000000
50%,366.500000,370.500000,22.000000,43.000000,2021.000000,6.000000,15.000000,16.000000
75%,549.250000,553.250000,25.000000,50.000000,2023.000000,9.000000,22.000000,19.000000
max,732.000000,736.000000,40.000000,80.000000,2023.000000,12.000000,31.000000,23.000000

In [9]:
data.head()

,Unnamed: 0.1,Unnamed: 0,Text,Sentiment,Timestamp,User,Platform,Hashtags,Retweets,Likes,Country,Year,Month,Day,Hour
0,0,0,Enjoying a beautiful day at the park! ...,Positive,2023-01-15 12:30:00,User123,Twitter,#Nature #Park,15.0,30.0,USA,2023,1,15,12
1,1,1,Traffic was terrible this morning. ...,Negative,2023-01-15 08:45:00,CommuterX,Twitter,#Traffic #Morning,5.0,10.0,Canada,2023,1,15,8
2,2,2,Just finished an amazing workout! 💪 ...,Positive,2023-01-15 15:45:00,FitnessFan,Instagram,#Fitness #Workout,20.0,40.0,USA,2023,1,15,15
3,3,3,Excited about the upcoming weekend getaway! ...,Positive,2023-01-15 18:20:00,AdventureX,Facebook,#Travel #Adventure,8.0,15.0,UK,2023,1,15,18
4,4,4,Trying out a new recipe for dinner tonight. ...,Neutral,2023-01-15 19:55:00,ChefCook,Instagram,#Cooking #Food,12.0,25.0,Australia,2023,1,15,19

In [10]:
print(data.columns)

Index(['Unnamed: 0.1', 'Unnamed: 0', 'Text', 'Sentiment', 'Timestamp', 'User',
       'Platform', 'Hashtags', 'Retweets', 'Likes', 'Country', 'Year', 'Month',
       'Day', 'Hour'],
      dtype='object')

In [11]:
# What is the overall distribution of sentiments (positive, negative, neutral) across the posts?

sentiment_distributed = data['Sentiment'].value_counts()

In [13]:
print(sentiment_distributed)

Sentiment
Positive           44
Joy                42
Excitement         32
Neutral            14
Contentment        14
                   ..
Adrenaline          1
Harmony             1
ArtisticBurst       1
Radiance            1
Elegance            1
Name: count, Length: 279, dtype: int64

In [14]:
data.head(30)

,Unnamed: 0.1,Unnamed: 0,Text,Sentiment,Timestamp,User,Platform,Hashtags,Retweets,Likes,Country,Year,Month,Day,Hour
0,0,0,Enjoying a beautiful day at the park! ...,Positive,2023-01-15 12:30:00,User123,Twitter,#Nature #Park,15.0,30.0,USA,2023,1,15,12
1,1,1,Traffic was terrible this morning. ...,Negative,2023-01-15 08:45:00,CommuterX,Twitter,#Traffic #Morning,5.0,10.0,Canada,2023,1,15,8
2,2,2,Just finished an amazing workout! 💪 ...,Positive,2023-01-15 15:45:00,FitnessFan,Instagram,#Fitness #Workout,20.0,40.0,USA,2023,1,15,15
3,3,3,Excited about the upcoming weekend getaway! ...,Positive,2023-01-15 18:20:00,AdventureX,Facebook,#Travel #Adventure,8.0,15.0,UK,2023,1,15,18
4,4,4,Trying out a new recipe for dinner tonight. ...,Neutral,2023-01-15 19:55:00,ChefCook,Instagram,#Cooking #Food,12.0,25.0,Australia,2023,1,15,19
5,5,5,Feeling grateful for the little things in lif...,Positive,2023-01-16 09:10:00,GratitudeNow,Twitter,#Gratitude #PositiveVibes,25.0,50.0,India,2023,1,16,9
6,6,6,Rainy days call for cozy blankets and hot coc...,Positive,2023-01-16 14:45:00,RainyDays,Facebook,#RainyDays #Cozy,10.0,20.0,Canada,2023,1,16,14
7,7,7,The new movie release is a must-watch! ...,Positive,2023-01-16 19:30:00,MovieBuff,Instagram,#MovieNight #MustWatch,15.0,30.0,USA,2023,1,16,19
8,8,8,Political discussions heating up on the timel...,Negative,2023-01-17 08:00:00,DebateTalk,Twitter,#Politics #Debate,30.0,60.0,USA,2023,1,17,8
9,9,9,Missing summer vibes and beach days. ...,Neutral,2023-01-17 12:20:00,BeachLover,Facebook,#Summer #BeachDays,18.0,35.0,Australia,2023,1,17,12
10,10,10,Just published a new blog post. Check it out!...,Positive,2023-01-17 15:15:00,BloggerX,Instagram,#Blogging #NewPost,22.0,45.0,USA,2023,1,17,15
11,11,11,Feeling a bit under the weather today. ...,Negative,2023-01-18 10:30:00,WellnessCheck,Twitter,#SickDay #Health,7.0,15.0,Canada,2023,1,18,10
12,12,12,Exploring the city's hidden gems. ...,Positive,2023-01-18 14:50:00,UrbanExplorer,Facebook,#CityExplore #HiddenGems,12.0,25.0,UK,2023,1,18,14
13,13,13,"New year, new fitness goals! 💪 ...",Positive,2023-01-18 18:00:00,FitJourney,Instagram,#NewYear #FitnessGoals,28.0,55.0,USA,2023,1,18,18
14,14,14,Technology is changing the way we live. ...,Neutral,2023-01-19 09:45:00,TechEnthusiast,Twitter,#Tech #Innovation,15.0,30.0,India,2023,1,19,9
15,15,15,Reflecting on the past and looking ahead. ...,Positive,2023-01-19 13:20:00,Reflections,Facebook,#Reflection #Future,20.0,40.0,USA,2023,1,19,13
16,16,16,Just adopted a cute furry friend! 🐾 ...,Positive,2023-01-19 17:10:00,PetAdopter,Instagram,#PetAdoption #FurryFriend,15.0,30.0,Canada,2023,1,19,17
17,17,17,Late-night gaming session with friends. ...,Positive,2023-01-20 00:05:00,GamerX,Twitter,#Gaming #LateNight,18.0,35.0,UK,2023,1,20,0
18,18,18,Attending a virtual conference on AI. ...,Neutral,2023-01-20 11:30:00,TechConference,Facebook,#AI #TechConference,25.0,50.0,USA,2023,1,20,11
19,19,19,Winter blues got me feeling low. ...,Negative,2023-01-20 15:15:00,WinterBlues,Instagram,#WinterBlues #Mood,8.0,15.0,USA,2023,1,20,15
20,20,20,Sipping coffee and enjoying a good book. ...,Positive,2023-01-21 08:40:00,Bookworm,Twitter,#Reading #CoffeeTime,22.0,45.0,India,2023,1,21,8
21,21,21,Exploring the world of virtual reality. ...,Positive,2023-01-21 13:20:00,VRExplorer,Facebook,#VR #VirtualReality,15.0,30.0,USA,2023,1,21,13
22,22,22,Productive day ticking off my to-do list. ...,Positive,2023-01-21 16:45:00,ProductivityPro,Instagram,#Productivity #WorkFromHome,30.0,60.0,USA,2023,1,21,16
23,23,23,Just finished a challenging workout routine. ...,Positive,2023-01-22 09:15:00,FitnessWarrior,Twitter,#Fitness #ChallengeAccepted,20.0,40.0,UK,2023,1,22,9
24,24,24,Celebrating a milestone at work! 🎉 ...,Positive,2023-01-22 14:30:00,CareerMilestone,Facebook,#Career #Milestone,12.0,25.0,Canada,2023,1,22,14
25,25,25,Sunday brunch with friends. ...,Positive,2023-01-22 12:00:00,BrunchBuddy,Instagram,#Brunch #Friends,15.0,30.0,UK,2023,1,22,12
26,27,28,Learning a new language for personal growth. ...,Positive,2023-01-23 16:20:00,LanguageLearner,Facebook,#LanguageLearning #PersonalGrowth,25.0,50.0,India,2023,1,23,16
27,28,29,Quiet evening with a good book. ...,Positive,2023-01-23 19:45:00,BookLover,Instagram,#Reading #QuietTime,15.0,30.0,Australia,2023,1,23,19
28,29,30,Reflecting on the importance of mental health...,Positive,2023-01-24 11:30:00,MentalHealthMatters,Twitter,#MentalHealth #SelfCare,22.0,45.0,USA,2023,1,24,11
29,30,31,New painting in progress! 🎨 ...,Positive,2023-01-24 15:00:00,ArtistInAction,Facebook,#Art #PaintingInProgress,12.0,25.0,Canada,2023,1,24,15

In [15]:
#Which platform generates the most engagement in terms of likes and retweets

platform_generates = data.groupby('Platform')[['Likes','Retweets']].sum()

In [16]:
platform_generates['total_generates'] = platform_generates['Likes']+ platform_generates['Retweets']

In [17]:
platform_generates_sorted = platform_generates.sort_values('total_generates')

In [44]:
print(platform_generates_sorted[['total_generates']].head())

            total_generates
Platform
Instagram           17464.0
Facebook            14516.0
Twitter              8727.0
Twitter              6441.0

In [18]:
print(platform_generates_sorted[['total_generates']].head(10))

            total_generates
Platform
Twitter              6441.0
Twitter              8727.0
Facebook            14516.0
Instagram           17464.0

In [19]:
data.head()

,Unnamed: 0.1,Unnamed: 0,Text,Sentiment,Timestamp,User,Platform,Hashtags,Retweets,Likes,Country,Year,Month,Day,Hour
0,0,0,Enjoying a beautiful day at the park! ...,Positive,2023-01-15 12:30:00,User123,Twitter,#Nature #Park,15.0,30.0,USA,2023,1,15,12
1,1,1,Traffic was terrible this morning. ...,Negative,2023-01-15 08:45:00,CommuterX,Twitter,#Traffic #Morning,5.0,10.0,Canada,2023,1,15,8
2,2,2,Just finished an amazing workout! 💪 ...,Positive,2023-01-15 15:45:00,FitnessFan,Instagram,#Fitness #Workout,20.0,40.0,USA,2023,1,15,15
3,3,3,Excited about the upcoming weekend getaway! ...,Positive,2023-01-15 18:20:00,AdventureX,Facebook,#Travel #Adventure,8.0,15.0,UK,2023,1,15,18
4,4,4,Trying out a new recipe for dinner tonight. ...,Neutral,2023-01-15 19:55:00,ChefCook,Instagram,#Cooking #Food,12.0,25.0,Australia,2023,1,15,19

# Which users have the highest average engagement (likes and retweets per post)

In [20]:
data['Likes'] = data['Likes'].fillna(0)        #here assuming of columns of likes and retweets
data['Retweets'] = data['Retweets'].fillna(0)

In [21]:
data['total_engagement'] = data['Likes']+data['Retweets'] #here storing of total engagement

In [22]:
user_engagement = data.groupby('User')[['Likes','Retweets','total_engagement']].mean()

In [23]:
user_engagement_sorted = user_engagement.sort_values('total_engagement', ascending=True)

In [24]:
print(user_engagement_sorted.head())

                    Likes  Retweets  total_engagement
User
CommuterX            10.0       5.0              15.0
StrugglingSoul       10.0       5.0              15.0
ApatheticObserver    15.0       7.0              22.0
DisgustedHeart       15.0       7.0              22.0
StagnantHeart        15.0       7.0              22.0

In [25]:
print(user_engagement_sorted.head(10))

                    Likes  Retweets  total_engagement
User
CommuterX            10.0       5.0              15.0
StrugglingSoul       10.0       5.0              15.0
ApatheticObserver    15.0       7.0              22.0
DisgustedHeart       15.0       7.0              22.0
StagnantHeart        15.0       7.0              22.0
WellnessCheck        15.0       7.0              22.0
CorruptedHeart       15.0       7.0              22.0
MundaneHeart         15.0       7.0              22.0
BitterHeart          15.0       7.0              22.0
MourningHeart        15.0       8.0              23.0